name: vistool_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.0.1
  - pandas=2.2.2
  - matplotlib=3.9.1
  - seaborn=0.12.2
  - jupyterlab=4.2.4
  - jupyterlab-spellchecker=0.8.4
  - pytest=8.3.2
  - flake8
  - black
  - hatch
  - nbqa
  - pip=24.0
  - ipywidgets  
  - pip:
    - openpyxl
    - xlrd
    - plotly
    - xlwt
